name: "CI"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "Tests"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: 1.13

      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Download Go Modules
        working-directory: tests
        run: |
          go mod download

      - name: Run Unit Tests
        run: |
          echo "Run Unit Tests"

      - name: Run Intergration Tests
        working-directory: tests
        run: |
          go test -v

