name: "Test Module"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    name: "TerraTest"
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_OWNER: project-manager-testing

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Setup gotestsum
        uses: autero1/action-gotestsum@v0.1.0
        with:
          gotestsum_version: 1.8.0

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.11
          terraform_wrapper: false

      - name: Run Unit Tests
        run: |
          cd test/
          gotestsum --format short-verbose -- -tags=unit
          gotestsum --format testname -- -tags=unit

      - name: Run Intergration Tests
        run: |
          cd test/
          go test -v -tags=integration
