name: Terraform

on:
  pull_request:

jobs:
  format:
    name: 'Run terraform fmt'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Terraform fmt
        run: |
          echo "terraform fmt -check -recursive -no-color -diff"

  validate:
    name: 'Run terraform validate'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Terraform Validate
        run: |
          echo "terraform init -backend=false"
          echo "terraform validate"
